AWSTemplateFormatVersion: 2010-09-09
Description: ECS Fargate setup for stockmarket service with ALB

Parameters:
  RDSHOST:
    Type: String
  RDSUSER:
    Type: String
  RDSPASSWORD:
    Type: String
  RDSDBNAME:
    Type: String
  RDSPORT:
    Type: String
    Default: "3306"
  AWSREGION:
    Type: String
  COGNITOUSERPOOLID:
    Type: String
  COGNITOAPPCLIENTID:
    Type: String
  COGNITOAPPCLIENTSECRET:
    Type: String
  FLASKSECRETKEY:
    Type: String
  ALPHAVANTAGEAPIKEY:
    Type: String
  REDDITCLIENTID:
    Type: String
  REDDITCLIENTSECRET:
    Type: String
  REDDITUSERAGENT:
    Type: String
  FINNHUBAPIKEY:
    Type: String
  AWSACCESSKEYID:
    Type: String
  AWSSECRETACCESSKEY:
    Type: String
  DYNAMODBCHATTABLE:
    Type: String
  HFTOKEN:
    Type: String
  APIURL:
    Type: String
  ImageURLStockMarket:
    Type: String
  VPCID:
    Type: String
  PUBLICSUBNET1:
    Type: String
  PUBLICSUBNET2:
    Type: String
  GROQAPIKEY:
    Type: String

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster

  StockMarketTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: stockmarket-task
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: "arn:aws:iam::303683327949:role/ecsTaskExecutionRole"
      TaskRoleArn: "arn:aws:iam::303683327949:role/ecsTaskRole"
      ContainerDefinitions:
        - Name: stockmarket_service
          Image: !Ref ImageURLStockMarket
          Essential: true
          PortMappings:
            - ContainerPort: 5000
          Environment:
            - Name: RDS_HOST
              Value: !Ref RDSHOST
            - Name: RDS_USER
              Value: !Ref RDSUSER
            - Name: RDS_PASSWORD
              Value: !Ref RDSPASSWORD
            - Name: RDS_DB_NAME
              Value: !Ref RDSDBNAME
            - Name: RDS_PORT
              Value: !Ref RDSPORT
            - Name: AWS_REGION
              Value: !Ref AWSREGION
            - Name: COGNITO_USER_POOL_ID
              Value: !Ref COGNITOUSERPOOLID
            - Name: COGNITO_CLIENT_ID
              Value: !Ref COGNITOAPPCLIENTID
            - Name: COGNITO_CLIENT_SECRET
              Value: !Ref COGNITOAPPCLIENTSECRET
            - Name: FLASK_SECRET_KEY
              Value: !Ref FLASKSECRETKEY
            - Name: ALPHA_VANTAGE_API_KEY
              Value: !Ref ALPHAVANTAGEAPIKEY
            - Name: REDDIT_CLIENT_ID
              Value: !Ref REDDITCLIENTID
            - Name: REDDIT_CLIENT_SECRET
              Value: !Ref REDDITCLIENTSECRET
            - Name: REDDIT_USER_AGENT
              Value: !Ref REDDITUSERAGENT
            - Name: FINNHUB_API_KEY
              Value: !Ref FINNHUBAPIKEY
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref AWSACCESSKEYID
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !Ref AWSSECRETACCESSKEY
            - Name: DYNAMODB_CHAT_TABLE
              Value: !Ref DYNAMODBCHATTABLE
            - Name: HF_TOKEN
              Value: !Ref HFTOKEN
            - Name: API_URL
              Value: !Ref APIURL
            - Name: GROQ_API_KEY
              Value: !Ref GROQAPIKEY

          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/stockmarket
              awslogs-region: !Ref AWSREGION
              awslogs-stream-prefix: ecs

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic
      VPCID: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ALB to talk to ECS
      VPCID: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: stockmarket-alb
      Scheme: internet-facing
      Subnets:
        - !Ref PUBLICSUBNET1
        - !Ref PUBLICSUBNET2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: stockmarket-tg
      Port: 5000
      Protocol: HTTP
      VPCID: !Ref VPCID
      TargetType: ip
      HealthCheckPath: /ping
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - Listener
    Properties:
      ServiceName: stockmarket-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref StockMarketTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ServiceSecurityGroup
          Subnets:
            - !Ref PUBLICSUBNET1
            - !Ref PUBLICSUBNET2
      LoadBalancers:
        - ContainerName: stockmarket_service
          ContainerPort: 5000
          TargetGroupArn: !Ref TargetGroup

Outputs:
  LoadBalancerDNS:
    Description: Public URL of your stockmarket service
    Value: !GetAtt LoadBalancer.DNSName